version: '3.0'
services:
  node:
    build : .
    container_name: brain_control_bsft
    expose:
      - 3000
    extra_hosts:
      - "cuad1.telmex.com:10.5.0.22"
    volumes:
      - ./node_projects:/opt/projects
    links:
      - redis
    restart : always
  redis:
    container_name: redis_bsft
    image : redis:5.0.3-alpine
    restart : always
  nats:
    container_name: nats_bsft
    image : nats
    restart : always
networks:
  default:
    external:
      name: sentryNetwork
